#!/bin/sh
#v10.0.2
globalconf="${workdir}/cbsd.conf";
CBSDMODULE="helpers"
MYARG="mode file"
MYOPTARG="jname"
MYDESC="redis configuration script"

set -e
. ${globalconf}
set +e

. ${subr}
. ${strings}
init $*

#defines
_MYDIR=$(dirname `realpath $0`)
SERVICE="redis"

#trap "INSTALLLOOP=0 ; clear; echo; echo \"Exit to shell. To return into bootstrap script, please type: cbsd wb_installer\";  echo" HUP INT ABRT BUS TERM EXIT

### MAIN Route ###
#set -e
    . ${_MYDIR}/wd_rediscfg.subr
#set +e

REDISCFG="/usr/local/etc/redis.conf"

case "${mode}" in
	"get")
		[ -z "${par}" ] && err 1 "${MAGENTA}par= is mandatory${NORMAL}"
		res=$(get_var ${par})
		echo ${res}
		;;
	"set")
		[ ! -f "${file}" ] && err 1 "No such file: ${file}"
		if [ -z "${jname}" ]; then
			root_path=""
			exec_cmd=""
		else
			. ${jrcconf}
			if [ $? -eq 1 ]; then
		err 1 "${MAGENTA}No such jail: ${GREEN}${jname}${NORMAL}"
		fi
		[ $jid -eq 0 ] && err 1 "${MAGENTA}Jail is not active: ${GREEN}${jname}${NORMAL}"
		root_path="${data}"
		exec_cmd="/usr/sbin/jexec ${jid}"
		fi
		cp ${REDISCFG} ${root_path}/${REDISCFG}.cbsd.bak
		cp ${file} ${root_path}/${REDISCFG}

		trap "mv ${root_path}/${REDISCFG}.cbsd.bak ${root_path}/${REDISCFG}; ${exec_cmd} /usr/sbin/service redis start >/dev/null 2>&1" HUP INT ABRT BUS TERM EXIT
		_res=$( ${exec_cmd} /usr/sbin/service redis stop >/dev/null 2>&1)
		_res=$( ${exec_cmd} /usr/sbin/service redis start 2>&1)

		if [ $? -eq 0 ]; then
			trap "" HUP INT ABRT BUS TERM EXIT
			err 0 "Done"
		fi
		err 1 "${_res}"
		;;
esac
