get_var()
{
	local _res=""
	[ -z "${1}" ] && return 0
	_res=$( grep -v "^#" ${REDISCFG} | /usr/bin/awk "/^$1/ "'{print substr($0, index($0,$2)) }' )
	[ -z "${_res}" ] && return 0
	echo ${_res}
}

set_var()
{
	local _bkp="${tmpdir}/myconf.$$"
	local _val

	[ -z "${1}" -o -z "${2}" ] && return 0
	_val=$( get_var $1 )
	if [ -z "${_val}" ]; then
		echo "$1 $2" >> ${REDISCFG}
	else
		cp ${REDISCFG} ${_bkp}
		grep -v "^$1" ${_bkp} > ${REDISCFG}
		echo "$1 $2" >> ${REDISCFG}
		rm -f ${_bkp}
	fi
}
